---
- name: install mysql
  apt: name={{ item }} 
    update_cache=yes 
    state=present
  become: yes
  become_user: su
  with_items:
    - python-mysqldb
    - mysql-server
- name: Start the MySQL service
  service: 
     name: mysql 
     state: started
     enabled: true
  become: yes
  become_user: su

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 
