---
- name: copy initial root user password file
  copy:
    src: .my.cnf
    dest: "/root/.my.cnf"
  become: yes
  become_method: sudo

- name: MySQL | Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password iloveit | sudo /usr/bin/debconf-set-selections
  
- name: install mysql
  apt: name={{ item }} 
    update_cache=yes 
    state=present
  become: yes
  become_method: sudo
  with_items:
    - python-mysqldb
    - mysql-server
  register: update_mysql

#- name: Install the Python MySQLB module
#  pip:
#    name: MySQL-python

- name: Start the MySQL service
  service: 
     name: mysql 
     state: started
     enabled: true
  become: yes
  become_method: sudo

- name: update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: iloveit 
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost 
  become: yes
  become_method: sudo 
