# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('currency_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_wallet_trxId', models.CharField(max_length=128, null=True)),
                ('order_type', models.CharField(choices=[(b'BUY', b'Buy'), (b'SELL', b'Sell')], max_length=8)),
                ('sub_type', models.CharField(default=b'', max_length=16)),
                ('units', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit_price_currency', models.CharField(choices=[(b'CYN', b'Renminbi'), (b'USD', b'US Dollar')], default=b'CYN', max_length=8)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('cryptocurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cryptocurrency')),
                ('reference_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('middle', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passwd_hash', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64)),
                ('config_json', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_at_provider', models.CharField(max_length=64)),
                ('provider_qrcode_image', models.ImageField(upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PaymentProvider')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('review_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='users.User')),
                ('target_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField()),
                ('trans_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_addr', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('lastupdated_by', models.IntegerField()),
                ('cryptocurrent_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cryptocurrency')),
            ],
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
