# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=128)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=32)),
                ('acct_qrcode_image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=8)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CryptoAccount')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('provider', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('config', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='externalpaymentmethod',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PaymentProvider'),
        ),
        migrations.AddField(
            model_name='externalpaymentmethod',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='cryptoaccount',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
