# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('currency_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_wallet_trxId', models.CharField(max_length=128, null=True)),
                ('order_type', models.CharField(choices=[(b'BUY', b'Buy'), (b'SELL', b'Sell')], max_length=8)),
                ('sub_type', models.CharField(choices=[(b'OPEN', b'Open'), (b'BUY_ON_ASK', b'Buy_on_ask'), (b'SELL_ON_BID', b'Sell_on_bid')], default=b'OPEN', max_length=16)),
                ('units', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit_price_currency', models.CharField(choices=[(b'CYN', b'Renminbi'), (b'USD', b'US Dollar')], default=b'CYN', max_length=8)),
                ('lock_count', models.IntegerField(default=0)),
                ('units_balance', models.FloatField()),
                ('units_available_to_trade', models.FloatField()),
                ('status', models.CharField(choices=[(b'OPEN', b'Open'), (b'CANCELLED', b'Cancelled'), (b'FILLED', b'Filled'), (b'PARTIALFILLED', b'PartialFilled'), (b'LOCKED', b'Locked')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('middle', models.CharField(default=b'', max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(default=b'', max_length=32)),
                ('config_json', models.TextField(default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('passwd_hash', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64)),
                ('config_json', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_created_by', to='users.UserLogin')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_lastupdated_by', to='users.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_at_provider', models.CharField(max_length=64)),
                ('provider_qrcode_image', models.ImageField(upload_to=b'uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPaymentMethod_created_by', to='users.UserLogin')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPaymentMethod_lastupdated_by', to='users.UserLogin')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PaymentProvider')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserReview_created_by', to='users.UserLogin')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserReview_lastupdated_by', to='users.UserLogin')),
                ('review_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='users.User')),
                ('target_userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField()),
                ('trans_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStatue_created_by', to='users.UserLogin')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStatue_lastupdated_by', to='users.UserLogin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_addr', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserWallet_created_by', to='users.UserLogin')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserWallet_lastupdated_by', to='users.UserLogin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'first', max_length=32, unique=True)),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_created_by', to='users.UserLogin')),
                ('cryptocurrency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cryptocurrency')),
                ('lastupdated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_lastupdated_by', to='users.UserLogin')),
            ],
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Wallet'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_created_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastupdated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_lastupdated_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentProvider_created_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='lastupdated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentProvider_lastupdated_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_created_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='order',
            name='cryptocurrencyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cryptocurrency'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastupdated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_lastupdated_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Wallet'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cryptocurrency_created_by', to='users.UserLogin'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='lastupdated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cryptocurrency_lastupdated_by', to='users.UserLogin'),
        ),
    ]
