---
- name: copy static sync script
  template: 
    src: apache_sync_statics.sh.j2
    dest: "{{ workspace_dir }}/xwjy/coinExchange/admin/apache_sync_statics.sh"
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: 0755

- name: sync the static
  command: ./apache_sync_statics.sh
  args:
    chdir: "{{ workspace_dir }}/xwjy/coinExchange/admin/"
  become: yes
  become_method: sudo

- name: copy right templates to code
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: 0644
  with_items:
  - { "src": "wsgi.py.j2", "dest":"{{ workspace_dir}}/xwjy/coinExchange/coinExchange/wsgi.py" }
  - { "src": "production.py.j2", "dest": "{{ workspace_dir}}/xwjy/coinExchange/coinExchange/settings/production.py" }
  - { "src": "dev.py.j2", "dest" : "{{ workspace_dir}}/xwjy/coinExchange/coinExchange/settings/dev.py" }
  notify:
    restart apache2
